version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wallet-data
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: walletDB
      MYSQL_USER: userWallet
      MYSQL_PASSWORD: userWallet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: wallet-api-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/walletDB
      SPRING_DATASOURCE_USERNAME: userWallet
      SPRING_DATASOURCE_PASSWORD: userWallet
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    depends_on:
      - db

volumes:
  db_data:
